// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PulseTrack.Persistence.Configurations;

#nullable disable

namespace PulseTrack.Persistence.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PulseTrack.Domain.Aggregates.Groups.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_groups_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("PulseTrack.Domain.Aggregates.Question.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_questions_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("PulseTrack.Domain.Aggregates.Question.Entities.QuestionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_question_items");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_question_items_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_items_question_id");

                    b.ToTable("question_items", (string)null);
                });

            modelBuilder.Entity("PulseTrack.Domain.Aggregates.Survey.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_surveys");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_surveys_id");

                    b.ToTable("surveys", (string)null);
                });

            modelBuilder.Entity("PulseTrack.Domain.Aggregates.Survey.Entities.SurveySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AcceptAnswer")
                        .HasColumnType("boolean")
                        .HasColumnName("accept_answer");

                    b.Property<bool>("CanEditAnswer")
                        .HasColumnType("boolean")
                        .HasColumnName("can_edit_answer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("SendNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("send_notification");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_id");

                    b.Property<Guid?>("SurveyId1")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_id1");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<bool>("UseDate")
                        .HasColumnType("boolean")
                        .HasColumnName("use_date");

                    b.Property<bool>("UseDuration")
                        .HasColumnType("boolean")
                        .HasColumnName("use_duration");

                    b.HasKey("Id")
                        .HasName("pk_survey_settings");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_survey_settings_id");

                    b.HasIndex("SurveyId1")
                        .IsUnique()
                        .HasDatabaseName("ix_survey_settings_survey_id1");

                    b.ToTable("survey_settings", (string)null);
                });

            modelBuilder.Entity("PulseTrack.Domain.Aggregates.Question.Entities.QuestionItem", b =>
                {
                    b.HasOne("PulseTrack.Domain.Aggregates.Question.Entities.Question", "Question")
                        .WithMany("Items")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_items_question_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PulseTrack.Domain.Aggregates.Survey.Entities.Survey", b =>
                {
                    b.HasOne("PulseTrack.Domain.Aggregates.Survey.Entities.SurveySettings", null)
                        .WithOne("Survey")
                        .HasForeignKey("PulseTrack.Domain.Aggregates.Survey.Entities.Survey", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surveys_survey_settings_id");
                });

            modelBuilder.Entity("PulseTrack.Domain.Aggregates.Survey.Entities.SurveySettings", b =>
                {
                    b.HasOne("PulseTrack.Domain.Aggregates.Survey.Entities.Survey", null)
                        .WithOne("Settings")
                        .HasForeignKey("PulseTrack.Domain.Aggregates.Survey.Entities.SurveySettings", "SurveyId1")
                        .HasConstraintName("fk_survey_settings_surveys_survey_id1");
                });

            modelBuilder.Entity("PulseTrack.Domain.Aggregates.Question.Entities.Question", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PulseTrack.Domain.Aggregates.Survey.Entities.Survey", b =>
                {
                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("PulseTrack.Domain.Aggregates.Survey.Entities.SurveySettings", b =>
                {
                    b.Navigation("Survey")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
